# Docker Compose Production Override
# This file provides production-specific configuration
# Copy to docker-compose.override.yml and customize for your deployment

version: '3.8'

services:
  app:
    image: aa42aa3571f0acc5d3b6129cdf461c245aa187cae67854b8c2878f39f679449c 
    # Production-specific environment overrides
    environment:
      # Override local data path if needed
      WARPSYNC_LOCAL_DATA_PATH: /app/data/local
      MONGODB_URI: 'mongodb://admin:ChangeMe%211@195.201.91.38:27017/warpsync?directConnection=true&authSource=admin'

    volumes:
      # Customize these volume mappings for your production environment
      # Example: Map your media server storage to the container
      # - /mnt/storage/media:/app/data/local
      # - /var/log/warpsync:/app/logs
      
      # Default mappings (customize these)
      - ./data/local:/Users/farschadhoshiar/Documents/media
      - ./logs:/app/logs

    ports:
      - "3000:3000"  # Expose app on port 3000
    
    # Health check for production monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Remove MongoDB dependency for production (using external database)
  mongodb:
    profiles:
      - disabled
