name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: [self-hosted, ARM64]
    environment:
      name: ${{ github.ref_name == 'main' && 'main' || github.ref_name == 'dev' && 'dev' }}

    env:
      NODE_ENV: production
      DOCKER_IMAGE: ghcr.io/farschadhoshiar/warpsync
      DOCKER_TAG: ${{ github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
            ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}-${{ github.run_number }}
            ${{ github.ref_name == 'main' && format('{0}:latest', env.DOCKER_IMAGE) || '' }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:latest
          cache-to: type=inline